[[ define "blockVolumeName" -]]
[[- $role := index . 0 -]]
[[- $block := index . 1 -]]
[[- $disk := index . 2 -]]
[[- printf "doris-%s-b%v-d%v" $role $block $disk -]]
[[- end ]]
[[ define "versionOverride" -]]
[[- $overrides := index . 0 -]]
[[- $key := index . 1 -]]
[[- $default := index . 2 -]]
[[- if hasKey $overrides $key -]]
[[- index $overrides $key -]]
[[- else -]]
[[- $default -]]
[[- end -]]
[[- end ]]
[[ define "storageRootPath" -]]
[[- $n := . -]]
[[- $paths := list -]]
[[- range $i := until $n -]]
[[- $paths = append $paths (printf "/opt/apache-doris/be/storage/data%v" (add1 $i)) -]]
[[- end -]]
[[- join ";" $paths -]]
[[- end ]]
